version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Asia/Tashkent
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '06:00'
      timezone: Asia/Tashkent
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
