import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const repositoryRoot = fileURLToPath(new URL('../', import.meta.url));
const packagePath = fileURLToPath(new URL('../package.json', import.meta.url));
const outputPath = fileURLToPath(
  new URL('../src/infrastructure/generated/version.ts', import.meta.url),
);
const checkOnly = process.argv.includes('--check');

const packageMetadata: unknown = JSON.parse(await readFile(packagePath, 'utf8'));
if (
  typeof packageMetadata !== 'object' ||
  packageMetadata === null ||
  !('version' in packageMetadata) ||
  typeof packageMetadata.version !== 'string' ||
  !/^[0-9A-Za-z.+-]+$/u.test(packageMetadata.version)
) {
  throw new Error('package.json must contain a safe SemVer-compatible version');
}

const generated =
  `// Generated by scripts/generate-version.ts from package.json. Do not edit.\n` +
  `// x-release-please-start-version\n` +
  `export const BROWSERMESH_VERSION = '${packageMetadata.version}' as const;\n` +
  `// x-release-please-end\n`;

if (checkOnly) {
  const current = await readFile(outputPath, 'utf8').catch(() => undefined);
  if (current !== generated) {
    throw new Error(
      `Generated version is stale. Run "npm run generate:version" in ${repositoryRoot}`,
    );
  }
} else {
  await writeFile(outputPath, generated, 'utf8');
}
